apiVersion: batch/v1
kind: CronJob
metadata:
  name: print-message
spec:
  schedule: "*/5 * * * *"  # Cron schedule expression for every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: busybox
            image: busybox
            command:
            - /bin/sh
            - -c
            - echo "40daysofkubernetes"
          restartPolicy: OnFailure
